# Generated by Django 3.2.25 on 2025-02-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0004_auto_20250224_0317'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='instructor',
            name='unique_instructor',
        ),
        migrations.AddConstraint(
            model_name='instructor',
            constraint=models.UniqueConstraint(fields=('last_name', 'first_name', 'disambiguator'), name='unique_instructor'),
        ),
    ]
