# Generated by Django 3.2.25 on 2025-02-24 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0005_auto_20250224_0318'),
    ]

    operations = [
    ]
